# Generated by Django 4.2.1 on 2023-07-08 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='CreatedBy', default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='CreatedOn')),
                ('modified_by', models.BigIntegerField(blank=True, db_column='ModifiedBy', default=0, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='ModifiedOn')),
                ('name', models.CharField(blank=None, db_column='Name', default=None, max_length=255)),
                ('local', models.CharField(blank=None, db_column='Local', default=None, max_length=255)),
                ('price', models.FloatField(db_column='Price', default=0)),
                ('city', models.CharField(blank=None, db_column='City', default=None, max_length=255)),
                ('type', models.CharField(blank=None, db_column='Type', default=None, max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', default=None, null=True)),
                ('date', models.DateTimeField(db_column='Date', default=None, null=True)),
                ('user', models.ForeignKey(db_column='UserId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
    ]
