# Generated by Django 4.2.1 on 2023-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_user_alter_eventparticipant_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='grade',
            field=models.IntegerField(db_column='Grade', default=0, null=True),
        ),
    ]
